version: 1.0.{build}
platform: x64
image: Visual Studio 2015
os: Visual Studio 2015
init:
- cmd: choco upgrade chocolatey
install:
- cmd: choco install tinycc
#- cmd: choco install mingw-get
before_build:
- echo Running cmake...
- cmd: cd src
- cmd: cmake -G"Visual Studio 14 2015 Win64"
- cmd: tcc -o ejem.exe -run helloworld.c
#- cmd: gcc helloworld.c -o helloworld.exe
- cmd: dir
build:
  parallel: true
  project: src/Project.sln
  verbosity: normal
after_build:
- cmd: cd Debug
- cmd: dir
artifacts:
  - path: hello.exe
    name: MyApp

  - path: logs
    name: test logs
    type: zip
